alias gss='git status'
alias gad='git add .'
alias gp='git push'
alias gpl='git pull'
alias gcm='git commit -m'
alias gd='git diff'

alias hs='history | grep'
alias hi='history'

alias code='~/Code'
alias drop='~/Dropbox'
alias desktop='~/Desktop'
alias tese='~/Desktop/Thesis/projecto-tese'
alias tdoc='open ~/Desktop/Thesis/projecto-tese/document.pdf'
alias wp='~/Desktop/weekly-programming'
alias h='cd ~'
alias dot='~/dotfiles'
